# Use the base image
FROM dustynv/ros:eloquent-ros-base-l4t-r32.7.1


# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python3-openssl \
    git

# Build and install Python 3.9
RUN wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz && \
    tar xzf Python-3.9.0.tgz && \
    cd Python-3.9.0 && \
    ./configure --enable-shared && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf Python-3.9.0* && \
    ldconfig

# Set Python 3.9 as the default version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 1

# Check the installed Python version
RUN python3 --version

# Continue with the rest of your Dockerfile...

